import type { Metadata } from "next";

import "./globals.css";

import { Providers } from "@/redux/provider";

import { inter } from "@/utils/fonts/Fonts";

export const metadata: Metadata = {
  title: "TizzTube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
